name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up build cache
        uses: actions/cache/restore@v4
        with:
          key: org-metrics-${{ hashfiles('.cache/**') }}
          path: ~/.cache
          restore-keys: |
            org-metrics-
    
      - name: General
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Student-Smart-Printing-Service-HCMUT

      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Student-Smart-Printing-Service-HCMUT
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4

      - name: Using graph charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stargazers.graph.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Student-Smart-Printing-Service-HCMUT
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph

      - name: Exclude Archived
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.archived.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Student-Smart-Printing-Service-HCMUT
          base: ""
          plugin_followup: yes
          plugin_followup_archived: no

      - name: Project from a repository
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.projects.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Student-Smart-Printing-Service-HCMUT
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          plugin_projects_descriptions: yes


      - name: Save build cache
        uses: actions/cache/save@v4
        with:
          key: org-metrics-${{ hashfiles('.cache/**') }}
          path: ~/.cache
