name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        id: cache-metrics-org
        uses: actions/cache@v3
        env:
          cache-name: cache-metrics
        with:
          path: ~/.cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    
      - if: ${{ steps.cache-metrics-org.outputs.cache-hit != 'true' }}
        name: General
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Student-Smart-Printing-Service-HCMUT

      - if: ${{ steps.cache-metrics-org.outputs.cache-hit != 'true' }}
        name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Student-Smart-Printing-Service-HCMUT
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4

      - if: ${{ steps.cache-metrics-org.outputs.cache-hit != 'true' }}
        name: Using graph charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stargazers.graph.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Student-Smart-Printing-Service-HCMUT
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph

      - if: ${{ steps.cache-metrics-org.outputs.cache-hit != 'true' }}
        name: Exclude Archived
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.archived.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Student-Smart-Printing-Service-HCMUT
          base: ""
          plugin_followup: yes
          plugin_followup_archived: no
